import { v } from "convex/values";

/** Validator for ingest: all fields optional; merged with defaults before db write. */
export const partialStudent = v.object({
  name: v.optional(v.string()),
  studentId: v.optional(v.string()),
  email: v.optional(v.string()),
  gender: v.optional(v.string()),
  age: v.optional(v.number()),
  address: v.optional(v.string()),
  famsize: v.optional(v.string()),
  Pstatus: v.optional(v.string()),
  Medu: v.optional(v.number()),
  Fedu: v.optional(v.number()),
  Mjob: v.optional(v.string()),
  Fjob: v.optional(v.string()),
  reason: v.optional(v.string()),
  guardian: v.optional(v.string()),
  traveltime: v.optional(v.number()),
  studytime: v.optional(v.number()),
  failures: v.optional(v.number()),
  schoolsup: v.optional(v.boolean()),
  famsup: v.optional(v.boolean()),
  paid: v.optional(v.boolean()),
  activities: v.optional(v.boolean()),
  nursery: v.optional(v.boolean()),
  higher: v.optional(v.boolean()),
  internet: v.optional(v.boolean()),
  romantic: v.optional(v.boolean()),
  famrel: v.optional(v.number()),
  freetime: v.optional(v.number()),
  goout: v.optional(v.number()),
  Dalc: v.optional(v.number()),
  Walc: v.optional(v.number()),
  health: v.optional(v.number()),
  absences: v.optional(v.number()),
  previousMarks: v.optional(v.number()),
});
